<?php
  /**
   * Theme definition for achievo default theme
   *
   * @package achievo
   * @subpackage themes
   *
   * @author boy <boy@ibuildings.nl>
   *
   * @copyright (c) 2005 Ibuildings.nl BV
   * @license http://www.gnu.org/copyleft/gpl.html GNU General Public License 2
   *
   * @version $Revision: 2193 $
   * $Id: themedef.inc 2193 2007-05-02 14:21:08Z guido $
   */

  /**
   * Theme definition
   */
  $theme["customtpls"] = 'scan templates/';
  $theme["graphBgColor"] = "#eeeeee";
  $theme['compatible_menus'] = array('achievo');
?>